# Generated by Django 5.1.7 on 2025-03-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tite_tag',
        ),
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
